\ir dropGameTables.sql
\ir dropMusTables.sql
\ir createMusTables.sql
\ir insertMusicdata.sql
\ir createGameTables.sql
\ir indexes.sql
\ir setUpCourses.sql
\ir setUpUsers.sql
\ir setUpResources.sql
\ir setUpCharacters.sql
\ir setUpAbilities.sql
\ir setUpItems.sql
